### ISSUE TITLE
请求短信接口报错

### ISSUE THREAD

**Issue by mitchhu** [hpyer/node-easysms#1]
问题：请求头和请求参数无法自定义配置。
报错原因：post请求参数第三方接口需要一个object，但是传过去的是string。

**Comment by hpyer** [comment]
哪个网关？

**Comment by mitchhu** [comment]
YunpianGateway

**Comment by hpyer** [comment]
请求的时候按json格式了，所以导致平台接受不到数据。请更新到v1.1.1版本再试下～

**Comment by ky-zhanglei** [comment]
能不能自测通过后再放出？

**Comment by hpyer** [comment]
@ky-zhanglei 
抱歉，我这边暂时没有相关账号，没法真实测试。不过我有按官方文档跑测试用例，是通过的。

如果你这边使用有问题可以反馈，也欢迎你修改代码后提交PR～

**Comment by ky-zhanglei** [comment]
> 

回复很及时啊，再接再厉，越做越好

**Comment by hpyer** [comment]
@ky-zhanglei 
感谢鼓励～
