### ISSUE TITLE
运行build之后dist目录下global.d.ts文件中导入Exception路径错误，并且interface GatewayConfigMap 接口提示错误

### ISSUE THREAD

**Issue by mitchhu** [hpyer/node-easysms#2]
<img width="441" alt="image" src="https://github.com/hpyer/node-easysms/assets/83808127/a555a103-dabe-462b-ba8f-7e814a8cccab">
<img width="416" alt="image" src="https://github.com/hpyer/node-easysms/assets/83808127/e79abf58-3441-410a-8b05-d66bcc5f9b41">

**Comment by hpyer** [comment]
已发布v1.1.2
